name: snake
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anyio=3.5.0=py37h06a4308_0
  - argon2-cffi=20.1.0=py37h27cfd23_1
  - attrs=21.4.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.10.0=pyh06a4308_0
  - black=22.6.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.6.15=ha878542_0
  - certifi=2022.6.15=py37h89c1867_0
  - cffi=1.15.0=py37hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.3=py37h89c1867_0
  - cryptography=36.0.0=py37h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.5.1=py37h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py37_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.11.3=py37h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.9.1=py37h06a4308_0
  - ipython=7.31.1=py37h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isort=5.10.1=pyhd8ed1ab_0
  - jedi=0.18.1=py37h06a4308_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9d=h7f8727e_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_core=4.9.2=py37h06a4308_0
  - jupyter_server=1.13.5=pyhd3eb1b0_0
  - jupyterlab=3.3.2=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libzlib=1.2.12=h166bdaf_2
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.0.1=py37h27cfd23_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - mypy_extensions=0.4.3=py37h89c1867_5
  - nbclassic=0.3.5=pyhd3eb1b0_0
  - nbclient=0.5.11=pyhd3eb1b0_0
  - nbconvert=6.4.4=py37h06a4308_0
  - nbformat=5.3.0=py37h06a4308_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.5=py37h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - notebook=6.4.8=py37h06a4308_0
  - numpy-base=1.21.5=py37hf524024_1
  - olefile=0.46=py37_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.5=h166bdaf_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.4.0=py37h5aabda8_0
  - pip=21.2.2=py37h06a4308_0
  - platformdirs=2.5.2=pyhd8ed1ab_1
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyrsistent=0.18.0=py37heee7806_0
  - pysocks=1.7.1=py37_1
  - python=3.7.12=hf930737_100_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.10.1=py3.7_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - pyzmq=22.3.0=py37h295c915_2
  - readline=8.1=h27cfd23_0
  - requests=2.27.1=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sniffio=1.2.0=py37h06a4308_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.37.0=hc218d9a_0
  - terminado=0.13.1=py37h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.11=h1ccaba5_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchaudio=0.10.1=py37_cu113
  - torchvision=0.11.2=py37_cu113
  - tornado=6.1=py37h27cfd23_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typed-ast=1.5.4=py37h540881e_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - websocket-client=0.58.0=py37h06a4308_4
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.12=h166bdaf_2
  - zstd=1.4.9=haebb681_0
  - pip:
    - apex==0.1
    - bbox==0.9.2
    - cycler==0.11.0
    - cython==0.28.2
    - imageio==2.13.5
    - imgaug==0.2.9
    - kiwisolver==1.3.2
    - matplotlib==3.4.3
    - networkx==2.6.3
    - numpy==1.16.4
    - opencv-contrib-python==3.4.2.17
    - opencv-python==3.4.2.17
    - protobuf==3.19.1
    - pycocotools==2.0.2
    - pyparsing==3.0.6
    - pyquaternion==0.9.9
    - pywavelets==1.1.1
    - pyyaml==6.0
    - scikit-image==0.17.2
    - scipy==1.5.4
    - shapely==1.8.0
    - tensorboardx==1.2
    - termcolor==1.1.0
    - tifffile==2021.11.2
    - tqdm==4.28.1
    - yacs==0.1.4
prefix: /home/ethan/miniconda3/envs/snake
